/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Hw3Import } from './routes/hw3'
import { Route as Hw2Import } from './routes/hw2'
import { Route as Hw1Import } from './routes/hw1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Hw3Route = Hw3Import.update({
  path: '/hw3',
  getParentRoute: () => rootRoute,
} as any)

const Hw2Route = Hw2Import.update({
  path: '/hw2',
  getParentRoute: () => rootRoute,
} as any)

const Hw1Route = Hw1Import.update({
  path: '/hw1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hw1': {
      preLoaderRoute: typeof Hw1Import
      parentRoute: typeof rootRoute
    }
    '/hw2': {
      preLoaderRoute: typeof Hw2Import
      parentRoute: typeof rootRoute
    }
    '/hw3': {
      preLoaderRoute: typeof Hw3Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  Hw1Route,
  Hw2Route,
  Hw3Route,
])

/* prettier-ignore-end */
